### ISSUE TITLE
Build a release of the plugin

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.logstash#3]
Build a binary release and provide its download the release section.

**Comment by 0xhansdampf** [comment]
I would suggest to push the plugin to rubygems: http://guides.rubygems.org/publishing/
(see section "PUBLISHING TO RUBYGEMS.ORG")

**Comment by FlorianLautenschlager** [comment]
That's a good point *and* would should also provide a release on github (release section of this repository).
